# Generated by Django 2.1 on 2019-04-23 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DelPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('orderedfrom', models.CharField(max_length=300)),
                ('productid', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(default='Delivered', max_length=20)),
                ('deliveredto', models.CharField(max_length=10)),
                ('datetime', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('phone', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only 0-9 are allowed.', 'Invalid Number'), django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)])),
                ('orderedfrom', models.CharField(max_length=300)),
                ('productid', models.IntegerField(null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(default='Undelivered', max_length=20)),
            ],
        ),
    ]
