# Generated by Django 2.1 on 2019-04-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sec_guard', '0004_auto_20190403_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='id',
        ),
        migrations.AlterField(
            model_name='package',
            name='productid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
