# Generated by Django 2.1 on 2019-04-17 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sec_guard', '0005_auto_20190403_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='orderedfrom',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='package',
            name='phone',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only 0-9 are allowed.', 'Invalid Number'), django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='package',
            name='productid',
            field=models.IntegerField(),
        ),
    ]
