# Generated by Django 2.1 on 2019-04-18 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sec_guard', '0008_auto_20190417_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='productid',
            field=models.IntegerField(null=True),
        ),
    ]
