# Generated by Django 2.1 on 2019-04-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sec_guard', '0009_auto_20190418_0404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='taken',
        ),
        migrations.AddField(
            model_name='package',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
