# Generated by Django 2.1 on 2019-04-18 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sec_guard', '0010_auto_20190418_0826'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('orderedfrom', models.CharField(max_length=300)),
                ('productid', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.RenameField(
            model_name='package',
            old_name='count',
            new_name='quantity',
        ),
    ]
