# Generated by Django 2.1 on 2019-04-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sec_guard', '0011_auto_20190418_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delpackage',
            name='datetime',
            field=models.CharField(max_length=50),
        ),
    ]
