# Generated by Django 2.1 on 2019-04-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sec_guard', '0012_auto_20190418_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='delpackage',
            name='status',
            field=models.CharField(default='Delivered', max_length=20),
        ),
        migrations.AddField(
            model_name='package',
            name='status',
            field=models.CharField(default='Undelivered', max_length=20),
        ),
    ]
